import { FormEvent, useEffect, useMemo, useState } from 'react'
import { parseApiError } from '../lib/api'

const API_BASE = import.meta.env.VITE_API_URL ?? 'http://localhost:3333'

type PaymentMethodKey = 'CARD' | 'UPI' | 'NET_BANKING' | 'WALLET'

type MethodConfig = {
  label: string
  description: string
  helper: string
  requiredFields: Array<keyof typeof fieldPlaceholders>
}

type FieldKey = 'cardToken' | 'upiId' | 'bankCode' | 'returnUrl' | 'walletProvider' | 'walletAccount'

type FieldValueMap = Record<FieldKey, string>

type CheckoutSavedMethod = {
  id: number
  maskedDisplay: string
  brand?: string | null
  expiryMonth?: number | null
  expiryYear?: number | null
  billingNickname?: string | null
  isDefault: boolean
  gatewayToken?: string | null
  method?: PaymentMethodKey | null
}

const fieldPlaceholders = {
  cardToken: 'Enter the token issued by the gateway (e.g. tok_abc123)',
  upiId: 'yourname@bank',
  bankCode: 'e.g. HDFC, ICICI',
  returnUrl: 'https://yourstore.com/checkout/complete',
  walletProvider: 'e.g. PayTM, GooglePay',
  walletAccount: 'Optional identifier (if required by provider)',
} satisfies Record<FieldKey, string>

const methodConfigs: Record<PaymentMethodKey, MethodConfig> = {
  CARD: {
    label: 'Card on file / hosted field',
    description: 'Complete the card authorization through our PCI-compliant gateway. We only collect the token.',
    helper: 'Provide the token generated by the hosted payment field. Do not enter raw card numbers.',
    requiredFields: ['cardToken'],
  },
  UPI: {
    label: 'UPI',
    description: 'Authenticate via your bank-supported UPI ID. ',
    helper: 'We will redirect you to the UPI app, so we only need your UPI handle.',
    requiredFields: ['upiId'],
  },
  NET_BANKING: {
    label: 'Net banking (provider-hosted)',
    description: 'Select your bank and approve in the bank-powered flow.',
    helper: 'Provide the bank code and browser return URL to handle the hosted flow.',
    requiredFields: ['bankCode', 'returnUrl'],
  },
  WALLET: {
    label: 'Wallet / digital pass',
    description: 'Approve payment using a linked wallet without revealing card numbers.',
    helper: 'Tell us which wallet provider you will use; account ID is optional.',
    requiredFields: ['walletProvider'],
  },
}

type RequestStatus = 'idle' | 'loading' | 'success' | 'error'

const CheckoutPage = () => {
  const [selectedMethod, setSelectedMethod] = useState<PaymentMethodKey>('CARD')
  const [fields, setFields] = useState<FieldValueMap>({
    cardToken: '',
    upiId: '',
    bankCode: '',
    returnUrl: 'https://yourstore.com/checkout/complete',
    walletProvider: '',
    walletAccount: '',
  })
  const [amount, setAmount] = useState('129.99')
  const [currency, setCurrency] = useState('USD')
  const [cartId, setCartId] = useState('42')
  const [status, setStatus] = useState<RequestStatus>('idle')
  const [message, setMessage] = useState<string>('Choose a payment method to begin authorization.')
  const [errors, setErrors] = useState<string[]>([])
  const [savedMethods, setSavedMethods] = useState<CheckoutSavedMethod[]>([])
  const [savedLoading, setSavedLoading] = useState(true)
  const [savedError, setSavedError] = useState<string | null>(null)
  const [selectedSavedMethodId, setSelectedSavedMethodId] = useState<number | null>(null)

  const methodConfig = methodConfigs[selectedMethod]

  useEffect(() => {
    const controller = new AbortController()
    setSavedLoading(true)
    setSavedError(null)
    fetch(`${API_BASE}/payment-methods`, {
      credentials: 'include',
      signal: controller.signal,
    })
      .then(async (response) => {
        if (!response.ok) {
          const message = await parseApiError(response, 'Unable to load saved payment methods.')
          throw new Error(message)
        }
        return response.json()
      })
      .then((data) => {
        const items = Array.isArray(data.items) ? data.items : []
        setSavedMethods(items)
      })
      .catch((err) => {
        if (controller.signal.aborted) {
          return
        }
        setSavedError(err instanceof Error ? err.message : 'Failed to load saved payment methods.')
      })
      .finally(() => {
        if (!controller.signal.aborted) {
          setSavedLoading(false)
        }
      })
    return () => controller.abort()
  }, [])

  const selectedSavedMethod = savedMethods.find((method) => method.id === selectedSavedMethodId) ?? null
  const isUsingSavedMethod = Boolean(selectedSavedMethod)

  const selectedSavedMethodLabel = useMemo(() => {
    if (selectedSavedMethod) {
      return selectedSavedMethod.billingNickname ?? selectedSavedMethod.maskedDisplay
    }
    return methodConfig.label
  }, [selectedSavedMethod, methodConfig.label])

  const handleFieldChange = (field: FieldKey, value: string) => {
    setFields((prev) => ({ ...prev, [field]: value }))
  }

  const validate = () => {
    const currentErrors: string[] = []
    methodConfig.requiredFields.forEach((field) => {
      if (!fields[field]?.trim()) {
        currentErrors.push(`${methodConfig.label} requires ${field.replace(/([A-Z])/g, ' $1').toLowerCase()}.`)
      }
    })
    if (!amount.trim() || Number.isNaN(Number(amount)) || Number(amount) <= 0) {
      currentErrors.push('Enter a valid amount greater than zero.')
    }
    if (!currency.trim()) {
      currentErrors.push('Currency is required.')
    }
    if (!cartId.trim()) {
      currentErrors.push('Cart ID is required to authorize payment.')
    }
    return currentErrors
  }

  const buildPayload = () => {
    const basePayload = {
      method: selectedMethod,
      amount: Number(Number(amount).toFixed(2)),
      currency: currency.trim().toUpperCase(),
      cartId: Number(cartId),
    }
    const detailPayload: Partial<Record<FieldKey, string>> = {}
    switch (selectedMethod) {
      case 'CARD':
        detailPayload.cardToken = fields.cardToken.trim()
        break
      case 'UPI':
        detailPayload.upiId = fields.upiId.trim()
        break
      case 'NET_BANKING':
        detailPayload.bankCode = fields.bankCode.trim()
        detailPayload.returnUrl = fields.returnUrl.trim()
        break
      case 'WALLET':
        detailPayload.walletProvider = fields.walletProvider.trim()
        if (fields.walletAccount.trim()) {
          detailPayload.walletAccount = fields.walletAccount.trim()
        }
        break
    }
    return { ...basePayload, ...detailPayload }
  }

  const buildSavedPayload = (method: CheckoutSavedMethod) => {
    const methodKey = method.method as PaymentMethodKey
    if (!methodKey || !(methodKey in methodConfigs)) {
      throw new Error('Saved payment method type is unrecognized. Please choose another method.')
    }
    const token = method.gatewayToken?.trim()
    if (!token) {
      throw new Error('Saved payment token is unavailable. Please add the method again to continue.')
    }
    const basePayload: Record<string, unknown> = {
      method: methodKey,
      amount: Number(Number(amount).toFixed(2)),
      currency: currency.trim().toUpperCase(),
      cartId: Number(cartId),
      metadata: { savedPaymentMethodId: method.id },
    }
    switch (methodKey) {
      case 'CARD':
        return { ...basePayload, cardToken: token }
      case 'UPI':
        return { ...basePayload, upiId: token }
      case 'NET_BANKING':
        return { ...basePayload, bankCode: token, returnUrl: fields.returnUrl.trim() }
      case 'WALLET':
        return { ...basePayload, walletProvider: token }
    }
  }

  const handleAuthorize = async (event: FormEvent) => {
    event.preventDefault()
    const validationErrors = isUsingSavedMethod ? [] : validate()
    if (validationErrors.length > 0) {
      setErrors(validationErrors)
      setStatus('error')
      setMessage('Please fix the highlighted issues before submitting.')
      return
    }

    if (isUsingSavedMethod && !selectedSavedMethod) {
      setErrors(['Select a saved payment method or switch to a new one.'])
      setStatus('error')
      return
    }

    setErrors([])
    setStatus('loading')
    setMessage(isUsingSavedMethod ? 'Authorizing via saved payment method…' : 'Sending authorization request…')

    let payload: Record<string, unknown>

    try {
      payload = isUsingSavedMethod
        ? buildSavedPayload(selectedSavedMethod!)
        : buildPayload()
    } catch (error) {
      setStatus('error')
      setMessage(error instanceof Error ? error.message : 'Unable to prepare payment request.')
      return
    }

    const idempotencyKey = typeof crypto !== 'undefined' && 'randomUUID' in crypto ? crypto.randomUUID() : String(Date.now())

    try {
      const response = await fetch(`${API_BASE}/payments/authorizations`, {
        method: 'POST',
        credentials: 'include',
        headers: {
          'Content-Type': 'application/json',
          'Idempotency-Key': idempotencyKey,
        },
        body: JSON.stringify(payload),
      })

      const body = await response.json().catch(() => null)
      if (!response.ok) {
        const serverMessage = body?.message ?? 'Unable to authorize payment at the moment.'
        setStatus('error')
        setMessage(serverMessage)
        return
      }

      const resolvedBody = body ?? {}
      const backendStatus = resolvedBody.status ?? resolvedBody.result?.status
      const normalizedStatus =
        typeof backendStatus === 'string' ? backendStatus.toLowerCase() : ''
      const success = normalizedStatus === 'authorized'
      const providerReference = resolvedBody.result?.providerReference ?? resolvedBody.providerReference
      const serverErrors = Array.isArray(resolvedBody.errors) ? resolvedBody.errors.filter(Boolean) : []
      const fallbackMessage =
        resolvedBody.message ??
        resolvedBody.result?.message ??
        'Payment was declined. Review the details and try again.'

      setStatus(success ? 'success' : 'error')
      if (success) {
        setErrors([])
        setMessage(`Payment authorized (ref: ${providerReference ?? 'unknown'}). Proceed to order review.`)
      } else {
        setErrors(serverErrors)
        setMessage(fallbackMessage)
      }
    } catch (error) {
      setStatus('error')
      setMessage('Unable to reach the payment service. Please try again shortly.')
    }
  }

  const requestSummary = useMemo(
    () => ({
      amount: Number(amount) || 0,
      currency: currency.trim().toUpperCase() || 'USD',
      cartId: Number(cartId) || 0,
      methodLabel: selectedSavedMethodLabel,
    }),
    [amount, currency, cartId, selectedSavedMethodLabel],
  )

  const handleSavedSelection = (methodId: number) => {
    setSelectedSavedMethodId((prev) => (prev === methodId ? prev : methodId))
    setStatus('idle')
    setMessage('Review the saved method and click authorize when ready.')
  }

  return (
    <section className="checkout-page">
      <header className="checkout-header">
        <p className="catalog-tag">Checkout</p>
        <h1>Authorize your payment</h1>
        <p className="muted">You can use a saved method or add a new one via the secure flow below.</p>
      </header>

      <div className="checkout-grid">
        <div className="checkout-form-area">
          <div className="saved-methods-panel">
            <header className="saved-methods-panel__header">
              <div>
                <p className="catalog-tag">Saved payment methods</p>
                <h3>Select a stored option</h3>
              </div>
              <button
                type="button"
                className="text-button"
                onClick={() => setSelectedSavedMethodId(null)}
              >
                Use a different method
              </button>
            </header>
            {savedLoading ? (
              <p className="muted">Loading saved payment options…</p>
            ) : savedError ? (
              <p className="status status--error">{savedError}</p>
            ) : savedMethods.length === 0 ? (
              <p className="muted">No saved payment methods found. Add one below.</p>
            ) : (
              <div className="saved-methods-grid">
                {savedMethods.map((method) => {
                  const expiry = method.expiryMonth && method.expiryYear
                    ? `${String(method.expiryMonth).padStart(2, '0')}/${method.expiryYear}`
                    : 'Expiry unknown'
                  const label = method.billingNickname ?? method.maskedDisplay
                  return (
                    <button
                      key={method.id}
                      type="button"
                      className={`saved-method-card ${selectedSavedMethodId === method.id ? 'is-selected' : ''}`}
                      onClick={() => handleSavedSelection(method.id)}
                      aria-pressed={selectedSavedMethodId === method.id}
                    >
                      <div className="saved-method-card__header">
                        <span className="saved-method-card__label">{label}</span>
                        {method.isDefault && <span className="saved-method-card__badge">Default</span>}
                      </div>
                      <p className="saved-method-card__details">
                        {method.maskedDisplay} • {method.brand ?? 'Tokenized'} • {expiry}
                      </p>
                    </button>
                  )
                })}
              </div>
            )}
            <p className="saved-method-note">
              Only tokenized payment references issued by your gateway are stored. No full card or wallet data is saved.
            </p>
          </div>

          <form className="checkout-form" onSubmit={handleAuthorize}>
            <div className="checkout-methods" role="group" aria-label="Payment method selection">
              {Object.entries(methodConfigs).map(([key, config]) => (
                <button
                  key={key}
                  type="button"
                  className={`checkout-method ${selectedMethod === key ? 'is-active' : ''}`}
                  onClick={() => {
                    setSelectedSavedMethodId(null)
                    setSelectedMethod(key as PaymentMethodKey)
                  }}
                >
                  <span className="checkout-method__label">{config.label}</span>
                  <span className="checkout-method__description">{config.description}</span>
                </button>
              ))}
            </div>

            <p className="checkout-helper">{methodConfig.helper}</p>

            {!isUsingSavedMethod && (
              <>
                {selectedMethod === 'CARD' && (
                  <label className="field">
                    <span>Card token</span>
                    <input
                      type="text"
                      placeholder={fieldPlaceholders.cardToken}
                      value={fields.cardToken}
                      onChange={(event) => handleFieldChange('cardToken', event.target.value)}
                    />
                  </label>
                )}

                {selectedMethod === 'UPI' && (
                  <label className="field">
                    <span>UPI ID</span>
                    <input
                      type="text"
                      placeholder={fieldPlaceholders.upiId}
                      value={fields.upiId}
                      onChange={(event) => handleFieldChange('upiId', event.target.value)}
                    />
                  </label>
                )}

                {selectedMethod === 'NET_BANKING' && (
                  <>
                    <label className="field">
                      <span>Bank code</span>
                      <input
                        type="text"
                        placeholder={fieldPlaceholders.bankCode}
                        value={fields.bankCode}
                        onChange={(event) => handleFieldChange('bankCode', event.target.value)}
                      />
                    </label>
                    <label className="field">
                      <span>Return URL</span>
                      <input
                        type="url"
                        placeholder={fieldPlaceholders.returnUrl}
                        value={fields.returnUrl}
                        onChange={(event) => handleFieldChange('returnUrl', event.target.value)}
                      />
                    </label>
                  </>
                )}

                {selectedMethod === 'WALLET' && (
                  <>
                    <label className="field">
                      <span>Wallet provider</span>
                      <input
                        type="text"
                        placeholder={fieldPlaceholders.walletProvider}
                        value={fields.walletProvider}
                        onChange={(event) => handleFieldChange('walletProvider', event.target.value)}
                      />
                    </label>
                    <label className="field">
                      <span>Wallet account (optional)</span>
                      <input
                        type="text"
                        placeholder={fieldPlaceholders.walletAccount}
                        value={fields.walletAccount}
                        onChange={(event) => handleFieldChange('walletAccount', event.target.value)}
                      />
                    </label>
                  </>
                )}
              </>
            )}

            <div className="checkout-input-grid">
              <label className="field">
                <span>Amount</span>
                <input
                  type="number"
                  min="0"
                  step="0.01"
                  value={amount}
                  onChange={(event) => setAmount(event.target.value)}
                  disabled={isUsingSavedMethod}
                />
              </label>
              <label className="field">
                <span>Currency</span>
                <input
                  type="text"
                  value={currency}
                  onChange={(event) => setCurrency(event.target.value)}
                  disabled={isUsingSavedMethod}
                />
              </label>
              <label className="field">
                <span>Cart ID</span>
                <input
                  type="number"
                  min="1"
                  step="1"
                  value={cartId}
                  onChange={(event) => setCartId(event.target.value)}
                  disabled={isUsingSavedMethod}
                />
              </label>
            </div>

            <button className="primary" type="submit" disabled={status === 'loading'}>
              {status === 'loading' ? 'Authorizing…' : 'Authorize payment'}
            </button>
          </form>

          <div
            className={`checkout-feedback status status--${status}`}
            role="status"
            aria-live="polite"
          >
            {message}
            {errors.length > 0 && (
              <ul className="error-list">
                {errors.map((error) => (
                  <li key={error}>{error}</li>
                ))}
              </ul>
            )}
          </div>
        </div>

        <div className="checkout-summary">
          <h2>Authorization summary</h2>
          <dl>
            <div>
              <dt>Selected method</dt>
              <dd>{requestSummary.methodLabel}</dd>
            </div>
            <div>
              <dt>Amount</dt>
              <dd>
                {requestSummary.currency} {requestSummary.amount.toFixed(2)}
              </dd>
            </div>
            <div>
              <dt>Currency</dt>
              <dd>{requestSummary.currency}</dd>
            </div>
            <div>
              <dt>Cart ID</dt>
              <dd>{requestSummary.cartId}</dd>
            </div>
          </dl>
          <p className="muted">
            After authorization, you can continue to the order review step without refreshing this page.
          </p>
        </div>
      </div>
    </section>
  )
}

export default CheckoutPage
